Feat, Style: Improve Import Icon Activity
Sketchware-Pro/Sketchware-Pro pull request #1171
Opened 2024-06-19 14:29 UTC by nethical6

Todo:
Replace pngs with vectors
Make vectors configurable

2024-06-19 22:35 UTC, ilyassesalama commented
Finally someone did it, great job!

2024-09-04 12:42 UTC, Yamenher commented
C'mon, I've been waiting for weeks for this pr to get merged, can you @nethical6 just finish it, that would be sooo freaking awesome 😃🔥

2024-09-04 16:18 UTC, remaker17 requested changes

2024-09-04 16:18 UTC, remaker17 commented on app/src/main/res/layout/manage_locallibraries.xml
> +<?xml version="1.0" encoding="utf-8"?>
Change PR title because of this changes.

2024-09-05 07:38 UTC, remaker17 commented
Can you also add some screenshots of your work?

2024-10-29 16:19 UTC, nethical6 commented
Known issues:
1. when setting background resource of a layout as a vector, the preview screen will fail to display it. however the background resource would be visible in the final compiled project.

2024-10-29 23:43 UTC, merged