Revert Material 3, Dynamic Colors Option, and Bottom Project Settings
Sketchware-Pro/Sketchware-Pro pull request #1512
Opened 2024-12-19 18:24 UTC by trindadedev13

2024-12-21 04:48 UTC, aikrq commented
I think it's not necessary to revert bottom sheet project options.

2024-12-21 05:26 UTC, trindadedev13 commented
> I think it's not necessary to revert bottom sheet project options.

donee

2024-12-21 05:45 UTC, aikrq requested changes

2024-12-21 05:45 UTC, aikrq commented on app/src/main/res/layout/dialog_project_settings.xml
> -                app:strokeWidth="0.5dp">
Why did you remove it?

2024-12-21 05:45 UTC, aikrq commented on app/src/main/res/layout/item_xml_command.xml
> -    app:strokeWidth="0.5dp">
This too.

2024-12-21 05:45 UTC, aikrq commented on app/src/main/res/layout/export_project.xml
> -                app:strokeWidth="0.5dp">
This too.

2024-12-21 05:45 UTC, aikrq commented on app/src/main/res/layout/dialog_project_settings.xml
> -                app:strokeWidth="0.5dp">
This too.

2024-12-21 05:45 UTC, aikrq commented on app/src/main/res/layout/dialog_project_settings.xml
> -                app:strokeWidth="0.5dp">
This too.

2024-12-21 05:52 UTC, trindadedev13 commented
@aikrq in response to all the "reviews":
I reverted all the commits that had to do with ProjectSettings, and in those commits, I had postponed these Attributes both in the ProjectSettings Layout and in the revised files

2024-12-21 06:31 UTC, aikrq commented
You can add them manually.

2024-12-21 15:32 UTC, trindadedev13 commented
done

2024-12-21 17:11 UTC, waelchateur commented
why ?? i am planing of pushing my changes for m3 and those feature are necessairy to use material components

2024-12-21 20:57 UTC, trindadedev13 commented
> why ?? i am planing to push my changes for m3 and those feature are necessairy to use material components

idk, for me this works fine, but the other devs said that this breaks old projects

2024-12-21 21:12 UTC, waelchateur commented
> > why ?? i am planing to push my changes for m3 and those feature are necessairy to use material components
> 
> idk, for me this works fine, but the other devs said that this breaks old projects

if those are turned off by default how they can affect old projects already tested a lot of projects and they work fine more many want m3 so here we r giving them m3 now they can make beautiful apps more you can disable them for minsdk21 like what i did cause no more future updates needed for old phones maybe only fixing some libs like firebase or onsignal or kotlin exept that your feature is very needed

2024-12-21 22:33 UTC, waelchateur commented
> > why ?? i am planing to push my changes for m3 and those feature are necessairy to use material components
> 
> idk, for me this works fine, but the other devs said that this breaks old projects

how about keeping enable_bridgeless_themes and if use material3 active it will be disabled and m3 theme injected instead

2024-12-22 02:00 UTC, aikrq commented
Why there's so many force pushes?

2024-12-22 03:14 UTC, trindadedev13 commented
> Why there's so many force pushes?

what problem?

2024-12-22 05:44 UTC, aikrq approved these changes

2024-12-22 05:44 UTC, merged

2024-12-24 14:44 UTC, RoyTheReal commented
No, PLEASE, don't get rid of the new material 3 + dynamic colors toggle, it works amazing! I was so happy to see that it was added. Way easier than adding it manually. Keep it in and just add a warning it _may_ break older projects. This feature is literally my favorite feature currently.

2024-12-24 14:50 UTC, RoyTheReal commented
BRING THE FEATURES BACK PLEASE! They are literally disabled on default. I tested the feature and it worked on ALL of my old projects.

2024-12-24 14:51 UTC, RoyTheReal commented
@trindadedev13 Dude revert this revert.

2024-12-24 14:59 UTC, Ohyeah66h commented
Yeah bring this feature back, literally just add a warning. Manually doing it never works correctly. The toggle is a huge quality of life enhancement

2024-12-24 16:20 UTC, hoxavel457 commented
I vote to bring this feature back as well. I love this feature.

2024-12-24 20:33 UTC, RoyTheReal commented
@trindadedev13 @aikrq A lot of people really want these features back, including me. Please, add them back. You guys are awesome :)

2024-12-24 20:34 UTC, Ohyeah66h commented
True :)

2024-12-28 13:08 UTC, RoyTheReal commented
@trindadedev13 Please bring the options back, I was using the feature