Add new docs and update exisiting ones
Sketchware-Pro/Sketchware-Pro pull request #557
Opened 2022-08-30 14:58 UTC by NiceSapien

You know🙏

2022-08-30 16:17 UTC, NiceSapien commented
Done👍

2022-08-30 17:38 UTC, JavkhlanK requested changes

2022-08-30 17:38 UTC, JavkhlanK commented on app/src/main/java/com/besome/sketch/beans/ComponentBean.java
> +                 return "https://sketchware-pro/docs/components/Firebase/cloud-messaging";
Wrong URL?

2022-08-31 08:26 UTC, NiceSapien commented on app/src/main/java/com/besome/sketch/beans/ComponentBean.java
> +                 return "https://sketchware-pro/docs/components/Firebase/cloud-messaging";
Damn

2022-08-31 08:42 UTC, JavkhlanK commented
I think the screenshots should be improved first before merging this.

![Example](https://user-images.githubusercontent.com/40118124/187636603-2112a2fd-e7c4-40ad-baad-aadb184a1a7c.png)

2022-08-31 08:44 UTC, NiceSapien commented
> I think the screenshots should be improved first before merging this.
> 
> ![Example](https://user-images.githubusercontent.com/40118124/187636603-2112a2fd-e7c4-40ad-baad-aadb184a1a7c.png)

ok bro lemme do it😔

2022-08-31 09:48 UTC, NiceSapien commented
> I think the screenshots should be improved first before merging this.
> 
> ![Example](https://user-images.githubusercontent.com/40118124/187636603-2112a2fd-e7c4-40ad-baad-aadb184a1a7c.png)

All Done

2022-08-31 14:25 UTC, JavkhlanK approved these changes
Everything alright now.

2022-08-31 14:25 UTC, merged

2022-09-24 19:58 UTC, khaled-0 commented
wouldn't it be better to host the docs at GitHub
you know, in the hosts branch.

2022-09-24 20:30 UTC, ilyassesalama commented
IMO, It'd be better to host the website entirely on GitHub.

2022-09-25 07:09 UTC, NiceSapien commented
Can't have multiple domains, test deployments etc. In it, also, already configured Vercel now. Ain't switching