Github Manager - to Push SourceCode
Sketchware-Pro/Sketchware-Pro pull request #863
Opened 2023-05-01 16:22 UTC by AndroXStudiO

2023-07-13 19:37 UTC, PranavPurwar requested changes

2023-07-13 19:37 UTC, PranavPurwar commented on app/src/main/java/com/besome/sketch/ProjectsFragment.java
> +import android.view.View.*;
Please prefer using explicit imports instead of wildcard imports

2023-07-13 19:37 UTC, PranavPurwar commented on app/src/main/java/com/besome/sketch/ProjectsFragment.java
> +              GitHubRepoCloner cloner = new GitHubRepoCloner(url.getText().toString(), repo, username.getText().toString(), token.getText().toString());
The username and token should be stored somewhere and not asked every time

2023-07-13 19:37 UTC, PranavPurwar commented on app/src/main/java/com/besome/sketch/ProjectsFragment.java
> +             }else{SketchwareUtil.toastError("Sorry! This repository is not usable in the Sketchware app.Try again.");prog.dismiss();}
formatting please

2023-07-13 19:37 UTC, PranavPurwar commented on app/src/main/java/com/besome/sketch/design/DesignActivity.java
> +                if (FileUtil.isExistFile(FileUtil.getExternalStorageDir()+"/.sketchware/data/"+sc_id+"/github_config") && !FileUtil.readFile(FileUtil.getExternalStorageDir()+"/.sketchware/data/"+sc_i
formatting

2023-07-13 19:37 UTC, PranavPurwar commented on app/src/main/java/com/besome/sketch/design/DesignActivity.java
> +               boolean isSucces = new PushToGitHub(DesignActivity.this,sc_id,false).pushREPO(filename.getText().toString(),Fileformat.getText().toString());
There is nothing that would notify the user if it was a success or not

2023-07-13 19:37 UTC, PranavPurwar commented on app/src/main/java/mod/RockAriful/AndroXStudio/GitHubRepoChecker.java
> +            Log.e(TAG, "Error checking repository: " + e.getMessage());
Same here

2023-07-13 19:37 UTC, PranavPurwar commented on app/src/main/java/mod/RockAriful/AndroXStudio/GitHubRepoChecker.java
> +
user agent is not needed

2023-07-13 19:37 UTC, PranavPurwar commented on app/src/main/java/mod/RockAriful/AndroXStudio/GitHubRepoCloner.java
> +		    _zip(filePath+name+"/DataSource",filePath+name+"/DataSource.swb");
Shouldn't the SWB file have a more appropriate name than `DataSource.swb`? You can use "SketchwareSource.swb` or something

2023-07-13 19:37 UTC, PranavPurwar commented on app/src/main/java/mod/RockAriful/AndroXStudio/GitHubRepoCloner.java
> +
???

2023-07-13 19:37 UTC, PranavPurwar commented on app/src/main/java/mod/RockAriful/AndroXStudio/GithubConfigActivity.java
> +		if (ContextCompat.checkSelfPermission(this, Manifest.permission.READ_EXTERNAL_STORAGE) == PackageManager.PERMISSION_DENIED
These permissions should already be granted by the time the user comes here, could be removed

2023-07-13 19:37 UTC, PranavPurwar commented on app/src/main/java/mod/RockAriful/AndroXStudio/GithubConfigActivity.java
> +		  	 }else{SketchwareUtil.toastError("Please enable GitHub service first!");}
The toast message does not make sense and is not useful

2023-07-13 19:37 UTC, PranavPurwar commented on app/src/main/java/mod/RockAriful/AndroXStudio/GithubConfigActivity.java
> +						else {
This nested if ... else loops can be merged and flattened with `else if`

2023-07-13 19:37 UTC, PranavPurwar commented on app/src/main/java/mod/RockAriful/AndroXStudio/GithubConfigActivity.java
> +                    } catch(Exception e){}
Silent error catching shouldn't be done

2023-07-13 19:37 UTC, PranavPurwar commented on app/src/main/java/mod/RockAriful/AndroXStudio/GithubLogActivity.java
> +     public  void _Uber_progress(final boolean _ifShow) {
uber???

2024-04-19 18:27 UTC, closed without merging

2024-04-20 01:27 UTC, ilyassesalama commented
This is a very good contribution in my opinion. Sad to see it go away like that.