Fix and Feat Custom Variable
Sketchware-Pro/Sketchware-Pro pull request #912
Opened 2023-07-14 17:26 UTC by elfilibusterismo

2023-07-14 18:12 UTC, JavkhlanK commented
why did you close the PR?? now the reviews are "gone"

2023-07-14 18:23 UTC, elfilibusterismo commented
> why did you close the PR?? now the reviews are "gone"

Sorry, I forgot.
If I'm not mistaken this is the exact review message

•an indent has 4 spaces
•after ifs, switches, etc. and before e.g. {s there should be a space
•and also very important: no stray lines before a class' fields (like in CustomVariableUtil.java) as well as before one's last }

2023-07-14 18:25 UTC, JavkhlanK commented
no, I also meant these:  
![image](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/40118124/9b859469-db5a-4aa5-b0d3-2d97b3d49979)

2023-07-14 18:41 UTC, elfilibusterismo commented
> no, I also meant these:  
> ![image](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/40118124/9b859469-db5a-4aa5-b0d3-2d97b3d49979)
> 

In validators class 
You said, remove the redundant 'this' and make the pattern static final.

LogicClickListener.java
For validator of modifier and type you've notice the error message not having colon
and for local variable not needed, so i just directly used toAdd.toString().trim()

ExtraPaletteBlock.java
You and hasrat said about Custom List being already exists, so I removed it from Custom Variable.

2023-07-14 18:42 UTC, JavkhlanK commented
nooo, I didn't ask you to list all and explain what you did, come on lol

2023-07-14 18:47 UTC, hasrat-ali commented
Why haven't you removed the new custom variable (6) yet?

Why you even need that?

2023-07-14 18:54 UTC, elfilibusterismo commented
> Why haven't you removed the new custom variable (6) yet?
> 
> Why you even need that?

![20230715_025426.png](https://github.com/Sketchware-Pro/Sketchware-Pro/assets/113604229/4df612c7-4e0c-41fd-ba33-f9dd484e215e)

2023-07-14 21:00 UTC, JavkhlanK requested changes

2023-07-14 21:01 UTC, JavkhlanK commented
please don't open another PR again after you make adjustments

2023-07-16 08:19 UTC, JavkhlanK requested changes

2023-07-16 08:19 UTC, JavkhlanK commented on app/src/main/java/dev/aldi/sayuti/block/ExtraPaletteBlock.java
Please undo the formatting you did to this file since it's unrelated to Custom Variables and in places like line 96 and the method `setBlock`, outright wrong.

2023-07-16 08:19 UTC, JavkhlanK commented on app/src/main/java/mod/elfilibustero/sketch/lib/valid/VariableModifierValidator.java
> +    public static final Pattern PATTERN_MODIFIER = Pattern.compile("\\b((public|protected|private)|static|final)(?!.*\\b\\1\\b)(\\s+((public|protected|private)|static|final)(?!.*\\b\\3\\b)){0,2}\\b")
after testing in Android Studio, even `final static private asdasd` matched and I don't think that's supposed to happen

2023-07-16 08:19 UTC, JavkhlanK commented on app/src/main/java/mod/elfilibustero/sketch/lib/valid/VariableTypeValidator.java
> +    public static final Pattern PATTERN_TYPE = Pattern.compile("^([a-zA-Z0-9]+)(<([a-zA-Z<>]+(?:\\s*,(?!.*?,)\\s*[a-zA-Z<>]+)*)>)?(\\[\\])?$");
generics still don't allow numbers, and `$` isn't allowed at all

2023-07-16 08:19 UTC, JavkhlanK commented on app/src/main/java/mod/elfilibustero/sketch/lib/valid/VariableTypeValidator.java
> +    public static final Pattern PATTERN_TYPE = Pattern.compile("^([a-zA-Z0-9]+)(<([a-zA-Z<>]+(?:\\s*,(?!.*?,)\\s*[a-zA-Z<>]+)*)>)?(\\[\\])?$");
also e.g. `List<?>`, `List<? extends Number>`, and `List<? super Number>` don't work

2023-07-16 08:19 UTC, JavkhlanK commented on app/src/main/java/mod/elfilibustero/sketch/lib/valid/VariableTypeValidator.java
> +    public static final Pattern PATTERN_TYPE = Pattern.compile("^([a-zA-Z0-9]+)(<([a-zA-Z<>]+(?:\\s*,(?!.*?,)\\s*[a-zA-Z<>]+)*)>)?(\\[\\])?$");
that's the reason I suggested raw input only, relying on the user to know what they're doing

2023-07-16 08:19 UTC, JavkhlanK commented on app/src/main/java/mod/elfilibustero/sketch/lib/utils/CustomVariableUtil.java
> +    public static final Pattern PATTERN_CUSTOM_VARIABLE = Pattern.compile("\\b((private|public|protected|static|final)\\s*)*([\\w$<>]+(?:\\s*,\\s*[\\w$<>]+)*(?:\\[\\])*)(?:\\s+([\\w$]+))(?:\\s*=\\s*(
for some reason `List<String> asd = new ArrayList<>()` isn't accepted

2023-07-16 08:19 UTC, JavkhlanK commented on app/src/main/java/mod/elfilibustero/sketch/lib/utils/CustomVariableUtil.java
> +    public static final Pattern PATTERN_CUSTOM_VARIABLE = Pattern.compile("\\b((private|public|protected|static|final)\\s*)*([\\w$<>]+(?:\\s*,\\s*[\\w$<>]+)*(?:\\[\\])*)(?:\\s+([\\w$]+))(?:\\s*=\\s*(
and like in VariableTypeValidator, `?` isn't handled properly

2023-07-16 08:19 UTC, JavkhlanK commented on app/src/main/java/mod/elfilibustero/sketch/lib/utils/CustomVariableUtil.java
> +    public static final Pattern PATTERN_CUSTOM_VARIABLE = Pattern.compile("\\b((private|public|protected|static|final)\\s*)*([\\w$<>]+(?:\\s*,\\s*[\\w$<>]+)*(?:\\[\\])*)(?:\\s+([\\w$]+))(?:\\s*=\\s*(
also looks like initializers also mustn't contain `()` or be literal Strings, otherwise it breaks

2023-07-16 08:19 UTC, JavkhlanK commented on app/src/main/java/mod/elfilibustero/sketch/lib/utils/CustomVariableUtil.java
> +
`\n`

2023-07-22 15:59 UTC, elfilibusterismo commented
Forgot to revert the format codes. Sorry

2023-07-23 07:26 UTC, JavkhlanK requested changes

2023-07-23 07:26 UTC, JavkhlanK commented on app/src/main/java/mod/hasrat/menu/ExtraMenuBean.java
> +                    menus.add(variableName != null? variableName : variable);
before the `?` of the ternary operator, there should be a space

2023-07-23 07:26 UTC, JavkhlanK commented on app/src/main/java/mod/hasrat/menu/ExtraMenuBean.java
> +                    menus.add(variableName != null? variableName : variable);
same ternary operator thing

2023-07-23 07:26 UTC, JavkhlanK commented on app/src/main/java/mod/hasrat/control/logic/LogicClickListener.java
> +         * (parameter) is in use.
could you undo formatting of this too?

2023-07-23 07:26 UTC, JavkhlanK commented on app/src/main/java/mod/hasrat/control/logic/LogicClickListener.java
> +                }
could you undo formatting of this too?

2023-07-23 07:26 UTC, JavkhlanK commented on app/src/main/java/mod/elfilibustero/sketch/lib/utils/CustomVariableUtil.java
> +    }
why should generics and array info be stripped? that way no `List<String>` or `File[]` Custom Variables can be created for example

2023-07-23 07:26 UTC, JavkhlanK commented on app/src/main/java/mod/elfilibustero/sketch/lib/utils/CustomVariableUtil.java
> +            "\\b((private|public|protected|static|final|transient|volatile)\\s+)*"
i think the modifier regex pattern should be extracted to a shared field

2023-07-23 07:26 UTC, JavkhlanK commented on app/src/main/java/mod/elfilibustero/sketch/lib/valid/VariableModifierValidator.java
> +    private Set<String> usedModifiers;
can be made final

2023-07-23 07:26 UTC, JavkhlanK commented on app/src/main/java/mod/elfilibustero/sketch/lib/valid/VariableModifierValidator.java
> +    private boolean hasAccessModifier;
only used in onTextChanged

2023-09-02 16:53 UTC, JavkhlanK commented on app/src/main/java/mod/elfilibustero/sketch/lib/utils/CustomVariableUtil.java
> +    }
@ilyassesalama why did you mark this as resolved too? it hasn't been yet.

2023-09-17 07:13 UTC, merged